import {
  LayoutDashboard,
  Users,
  ShieldCheck,
  Menu as MenuIcon,
  Package,
  ClipboardList,
  Plane,
  Settings,
  Activity,
  History,
  Radar,
  Store,
  LucideIcon,
} from 'lucide-react';
import { User, Role, MenuItem, DroneOrder, DroneProject, OrderStatus, UserRole } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    userId: 'u1',
    username: 'admin_cloud',
    email: 'admin@cloudgo.com',
    role: UserRole.ADMIN,
    status: 0,
    createTime: '2023-10-01',
  },
  {
    id: 2,
    userId: 'u2',
    username: 'pilot_jason',
    email: 'jason@cloudgo.com',
    role: UserRole.PILOT,
    status: 0,
    createTime: '2023-10-05',
  },
  {
    id: 3,
    userId: 'u3',
    username: 'disp_mary',
    email: 'mary@cloudgo.com',
    role: UserRole.DISPATCHER,
    status: 1,
    createTime: '2023-10-10',
  },
  {
    id: 4,
    userId: 'u4',
    username: 'pilot_sarah',
    email: 'sarah@cloudgo.com',
    role: UserRole.PILOT,
    status: 0,
    createTime: '2023-10-12',
  },
  {
    id: 5,
    userId: 'u5',
    username: 'pilot_mike',
    email: 'mike@cloudgo.com',
    role: UserRole.PILOT,
    status: 0,
    createTime: '2023-10-15',
  },
  {
    id: 6,
    userId: 'u6',
    username: 'pilot_alex',
    email: 'alex@cloudgo.com',
    role: UserRole.PILOT,
    status: 0,
    createTime: '2023-10-18',
  },
  {
    id: 7,
    userId: 'u7',
    username: 'pilot_emma',
    email: 'emma@cloudgo.com',
    role: UserRole.PILOT,
    status: 0,
    createTime: '2024-01-10',
  },
];

export const INITIAL_ROLES: Role[] = [
  { id: '1', name: 'Administrator', description: 'Full system access', permissions: ['all'] },
  {
    id: '2',
    name: 'Dispatcher',
    description: 'Manage orders and pilots',
    permissions: ['orders.view', 'orders.edit', 'projects.view'],
  },
  {
    id: '3',
    name: 'Pilot',
    description: 'View assigned tasks and update progress',
    permissions: ['orders.view', 'tasks.update'],
  },
];

export const INITIAL_MENU: MenuItem[] = [
  { id: '1', label: 'dashboard', path: '/', icon: 'LayoutDashboard' },
  { id: '2', label: 'systemAdmin', path: '/system', icon: 'Settings' },
  { id: '2.1', label: 'userMgmt', path: '/system/users', icon: 'Users', parentId: '2' },
  { id: '2.2', label: 'roleMgmt', path: '/system/roles', icon: 'ShieldCheck', parentId: '2' },
  { id: '2.4', label: 'auditLogs', path: '/system/logs', icon: 'History', parentId: '2' },
  { id: '2.3', label: 'menuMgmt', path: '/system/menu', icon: 'MenuIcon', parentId: '2' },
  { id: '2.5', label: 'customerMgmt', path: '/system/customers', icon: 'Users', parentId: '2' },
  { id: '3', label: 'droneServices', path: '/services', icon: 'Plane' },
  { id: '3.5', label: 'serviceHall', path: '/services/hall', icon: 'Store', parentId: '3' },
  { id: '3.1', label: 'orderMgmt', path: '/services/orders', icon: 'ClipboardList', parentId: '3' },
  {
    id: '3.3',
    label: 'visualDashboard',
    path: '/services/visual-dashboard',
    icon: 'Radar',
    parentId: '3',
  },
  {
    id: '3.2',
    label: 'projectCatalog',
    path: '/services/projects',
    icon: 'Package',
    parentId: '3',
  },
  {
    id: '3.4',
    label: 'projectCategoryMgmt',
    path: '/services/categories',
    icon: 'Settings',
    parentId: '3',
  },
];

export const INITIAL_ORDERS: DroneOrder[] = [
  {
    id: 1,
    planNo: 'ORD-2023-001',
    orderNumber: 'ORD-2023-001',
    projectName: 'Wedding Aerials',
    clientName: 'John Doe',
    userId: '2',
    pilotName: 'Jason',
    pilotId: '2',
    amount: 1200,
    budgetAmount: 1200,
    status: OrderStatus.IN_PROGRESS,
    date: '2023-11-20',
    createTime: '2023-11-20',
    desiredStartTime: '2023-11-20',
    location: 'Central Park, NY',
    departurePlace: 'Central Park, NY',
  },
  {
    id: 2,
    planNo: 'ORD-2023-002',
    orderNumber: 'ORD-2023-002',
    projectName: 'Farm Inspection',
    clientName: 'AgriCorp',
    userId: '4',
    pilotName: 'Sarah',
    pilotId: '4',
    amount: 3500,
    budgetAmount: 3500,
    status: OrderStatus.IN_PROGRESS,
    date: '2023-11-21',
    createTime: '2023-11-21',
    desiredStartTime: '2023-11-21',
    location: 'Valley Farm, CA',
    departurePlace: 'Valley Farm, CA',
  },
  {
    id: 3,
    planNo: 'ORD-2023-003',
    orderNumber: 'ORD-2023-003',
    projectName: 'Real Estate Shot',
    clientName: 'Modern Living',
    userId: 'unknown',
    amount: 800,
    budgetAmount: 800,
    status: OrderStatus.PENDING,
    date: '2023-11-22',
    createTime: '2023-11-22',
    desiredStartTime: '2023-11-22',
    location: 'Malibu, CA',
    departurePlace: 'Malibu, CA',
  },
  {
    id: 4,
    planNo: 'ORD-2023-004',
    orderNumber: 'ORD-2023-004',
    projectName: 'Bridge Inspection',
    clientName: 'City Council',
    userId: '5',
    pilotName: 'Mike',
    pilotId: '5',
    amount: 5000,
    budgetAmount: 5000,
    status: OrderStatus.IN_PROGRESS,
    date: '2023-11-23',
    createTime: '2023-11-23',
    desiredStartTime: '2023-11-23',
    location: 'Golden Gate, SF',
    departurePlace: 'Golden Gate, SF',
  },
  {
    id: 5,
    planNo: 'ORD-2023-005',
    orderNumber: 'ORD-2023-005',
    projectName: 'Music Festival',
    clientName: 'EventFlow',
    userId: '6',
    pilotName: 'Alex',
    pilotId: '6',
    amount: 2500,
    budgetAmount: 2500,
    status: OrderStatus.IN_PROGRESS,
    date: '2023-11-24',
    createTime: '2023-11-24',
    desiredStartTime: '2023-11-24',
    location: 'Coachella Valley, CA',
    departurePlace: 'Coachella Valley, CA',
  },
  {
    id: 6,
    planNo: 'ORD-2023-006',
    orderNumber: 'ORD-2023-006',
    projectName: 'Forest Monitoring',
    clientName: 'EcoWatch',
    userId: 'unknown',
    amount: 1800,
    budgetAmount: 1800,
    status: OrderStatus.PENDING,
    date: '2023-11-25',
    createTime: '2023-11-25',
    desiredStartTime: '2023-11-25',
    location: 'Redwood State Park',
    departurePlace: 'Redwood State Park',
  },
  {
    id: 7,
    planNo: 'ORD-2023-007',
    orderNumber: 'ORD-2023-007',
    projectName: 'Port Security',
    clientName: 'SeaGate',
    userId: '7',
    pilotName: 'Emma',
    pilotId: '7',
    amount: 4200,
    budgetAmount: 4200,
    status: OrderStatus.IN_PROGRESS,
    date: '2023-11-26',
    createTime: '2023-11-26',
    desiredStartTime: '2023-11-26',
    location: 'Port of Long Beach',
    departurePlace: 'Port of Long Beach',
  },
  {
    id: 8,
    planNo: 'ORD-2024-001',
    orderNumber: 'ORD-2024-001',
    projectName: 'Solar Farm Survey',
    clientName: 'GreenPower',
    userId: '2',
    pilotName: 'Jason',
    pilotId: '2',
    amount: 2800,
    budgetAmount: 2800,
    status: OrderStatus.IN_PROGRESS,
    date: '2024-01-02',
    createTime: '2024-01-02',
    desiredStartTime: '2024-01-02',
    location: 'Nevada Desert',
    departurePlace: 'Nevada Desert',
  },
  {
    id: 9,
    planNo: 'ORD-2024-002',
    orderNumber: 'ORD-2024-002',
    projectName: 'Dam Inspection',
    clientName: 'HydroCorp',
    userId: 'unknown',
    amount: 6500,
    budgetAmount: 6500,
    status: OrderStatus.PENDING,
    date: '2024-01-04',
    createTime: '2024-01-04',
    desiredStartTime: '2024-01-04',
    location: 'Hoover Dam, AZ',
    departurePlace: 'Hoover Dam, AZ',
  },
];

export const INITIAL_PROJECTS: DroneProject[] = [
  {
    id: 1,
    projectNo: 'P1',
    projectName: 'Real Estate Photography',
    typeNo: 'Photography',
    projectCode: 'PHOTO-001',
    unit: 'Project',
    projectPrice: 500,
    description: 'High-res 4K aerial shots for property listings.',
    isActive: 1,
    createTime: '2025-12-30T10:00:00',
    updateTime: '2025-12-30T10:00:00',
  },
  {
    id: 2,
    projectNo: 'P2',
    projectName: 'Crop Spraying',
    typeNo: 'Agricultural',
    projectCode: 'AGRI-002',
    unit: 'Acre',
    projectPrice: 2000,
    description: 'Automated liquid fertilizer spraying for large fields.',
    isActive: 1,
    createTime: '2025-12-30T10:00:00',
    updateTime: '2025-12-30T10:00:00',
  },
];

export const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Users,
  ShieldCheck,
  MenuIcon,
  Package,
  ClipboardList,
  Plane,
  Settings,
  Activity,
  History,
  Radar,
  Store,
};
